version: '3'
services:
  server:
    build:
      dockerfile: ./server/Dockerfile
      context: .
    image: eu.gcr.io/adaptive-reactive-analytics/reactive-analytics-server:0.8
    container_name: reactive-analytics-server
    ports:
      - '4000:4000'
  client:
    build:
      dockerfile: ./client/Dockerfile
      context: .
    image: eu.gcr.io/adaptive-reactive-analytics/reactive-analytics-client:0.8
    container_name: reactive-analytics-client
    ports:
      - '3000:3000'
    depends_on:
      - server
