apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: analytics-ingress
  annotations:
    kubernetes.io/ingress.class: 'nginx'
spec:
  tls:
    - hosts:
        - ${NAMESPACE}-reactive-analytics.adaptivecluster.com
      secretName: nginx-ingress-tls
  backend:
    serviceName: analytics-client
    servicePort: 3000
  rules:
    - host: ${NAMESPACE}-reactive-analytics.adaptivecluster.com
      http:
        paths:
          - path: /
            backend:
              serviceName: analytics-client
              servicePort: 3000

          - path: /subscriptions
            backend:
              serviceName: analytics-server
              servicePort: 4000

          - path: /graphql
            backend:
              serviceName: analytics-server
              servicePort: 4000

          - path: /healthz
            backend:
              serviceName: analytics-server
              servicePort: 4000

          - path: /iexsandbox
            backend:
              serviceName: analytics-server
              servicePort: 4000
